site_name: ebpfangel docs
site_url: https://tomasphilippart.github.io/ebpfangel
repo_url: https://github.com/TomasPhilippart/ebpfangel
theme:
  logo: assets/ebpfangel-bee-logo.png
  favicon: assets/ebpfangel-bee-logo.png

  icon:
    repo: fontawesome/brands/github

  name: material
  palette:

    - media: "(prefers-color-scheme)"
      scheme: custom
      toggle:
        icon: material/brightness-auto
        name: Switch to auto mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        primary: deep orange
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs.sticky
    - toc.integrate 
    - navigation.top
    - navigation.tabs
    - toc.follow
    - navigation.footer
    - navigation.path
    - content.code.copy

plugins:
    - search
    - awesome-pages
    - mkdocs-pdf

nav:
  - Overview: index.md
  - Simulator: simulator.md
  - Detector: detector.md
  - Machine Learning: machinelearning.md
  - Paper: paper.md
  - Slides: slides.md

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/TomasPhilippart
    - icon: fontawesome/brands/linkedin 
      link: https://linkedin.com/in/tomasphilippart

markdown_extensions:
  - toc
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2024 Tomás Philippart
